moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/79437/record/SDF/?record_type=3d&response_type=display" hugo new 1,3,7-trimethylurate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/70346/record/SDF/?record_type=3d&response_type=display" hugo new 1,3-dimethylurate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/91611/record/SDF/?record_type=3d&response_type=display" hugo new 1,7-dimethylurate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/53480452/record/SDF/?record_type=3d&response_type=display" hugo new 11beta-hydroxyandrosterone_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/131701047/record/SDF/?record_type=3d&response_type=display" hugo new 11-ketoetiocholanolone_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/75810/record/SDF/?record_type=3d&response_type=display" hugo new 1-methyl-4-imidazoleacetate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/89851/record/SDF/?record_type=3d&response_type=display" hugo new 1-methyl-5-imidazoleacetate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/92105/record/SDF/?record_type=3d&response_type=display" hugo new 1-methylhistidine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/69726/record/SDF/?record_type=3d&response_type=display" hugo new 1-methylurate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/440569/record/SDF/?record_type=3d&response_type=display" hugo new 1-ribosyl-imidazoleacetate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/222158/record/SDF/?record_type=3d&response_type=display" hugo new 2,3-dihydroxy-2-methylbutyrate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/154603736/record/SDF/?record_type=3d&response_type=display" hugo new 2,3-dihydroxy-5-methylthio-4-pentenoate_DMTPA.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/21933884/record/SDF/?record_type=3d&response_type=display" hugo new 2,3-dihydroxyisovalerate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/9338/record/SDF/?record_type=3d&response_type=display" hugo new 2,6-dihydroxybenzoic_acid.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/12196936/record/SDF/?record_type=3d&response_type=display" hugo new 2-aminophenol_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/10253/record/SDF/?record_type=3d&response_type=display" hugo new 2-hydroxyhippurate_salicylurate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/5280523/record/SDF/?record_type=3d&response_type=display" hugo new 2-isopropylmalate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/161227/record/SDF/?record_type=3d&response_type=display" hugo new 2-keto-3-deoxy-gluconate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/155342007/record/SDF/?record_type=3d&response_type=display" hugo new 2-methoxyhydroquinone_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/155342007/record/SDF/?record_type=3d&response_type=display" hugo new 2-methoxyhydroquinone_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/439459/record/SDF/?record_type=3d&response_type=display" hugo new 2-methylcitrate/homocitrate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/91825610/record/SDF/?record_type=3d&response_type=display" hugo new 2-methylmalonylcarnitine_C4-DC.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/54726398/record/SDF/?record_type=3d&response_type=display" hugo new 2-O-methylascorbic_acid.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/67147265/record/SDF/?record_type=3d&response_type=display" hugo new 2-oxo-1-pyrrolidinepropionate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/13120901/record/SDF/?record_type=3d&response_type=display" hugo new 2R,3R-dihydroxybutyrate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/171198/record/SDF/?record_type=3d&response_type=display" hugo new 3-3-amino-3-carboxypropyluridine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/118035223/record/SDF/?record_type=3d&response_type=display" hugo new 3-3-hydroxyphenylpropionate_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/193283/record/SDF/?record_type=3d&response_type=display" hugo new 3,4-dihydroxyphenylacetate_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/5200225/record/SDF/?record_type=3d&response_type=display" hugo new 3-amino-2-piperidone.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/64956/record/SDF/?record_type=3d&response_type=display" hugo new 3-aminoisobutyrate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/440403/record/SDF/?record_type=3d&response_type=display" hugo new 3-hydroxy-2-methylpyridine_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/1662/record/SDF/?record_type=3d&response_type=display" hugo new 3-hydroxy-3-methylglutarate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/18630403/record/SDF/?record_type=3d&response_type=display" hugo new 3-hydroxybutyroylglycine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/450268/record/SDF/?record_type=3d&response_type=display" hugo new 3-hydroxyhippurate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/129830950/record/SDF/?record_type=3d&response_type=display" hugo new 3-hydroxyhippurate_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/129846758/record/SDF/?record_type=3d&response_type=display" hugo new 3-hydroxyphenylacetate_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/440732/record/SDF/?record_type=3d&response_type=display" hugo new 3-hydroxyphenylacetoylglutamine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/7971/record/SDF/?record_type=3d&response_type=display" hugo new 3-hydroxypyridine_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/46173781/record/SDF/?record_type=3d&response_type=display" hugo new 3-hydroxystachydrine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/129892430/record/SDF/?record_type=3d&response_type=display" hugo new 3-methoxycatechol_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/1670/record/SDF/?record_type=3d&response_type=display" hugo new 3-methoxytyrosine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/340/record/SDF/?record_type=3d&response_type=display" hugo new 3-methyl_catechol_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/6999745/record/SDF/?record_type=3d&response_type=display" hugo new 3-methyladipate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/1551552/record/SDF/?record_type=3d&response_type=display" hugo new 3-methylglutaconate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/128145/record/SDF/?record_type=3d&response_type=display" hugo new 3-methylglutarylcarnitine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/11804/record/SDF/?record_type=3d&response_type=display" hugo new 3-methylurate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/165337/record/SDF/?record_type=3d&response_type=display" hugo new 3-S-cysteinyl-2-methylpropanoate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/18189/record/SDF/?record_type=3d&response_type=display" hugo new 4-acetamidobutanoate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/1983/record/SDF/?record_type=3d&response_type=display" hugo new 4-acetamidophenol.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/4022661/record/SDF/?record_type=3d&response_type=display" hugo new 4-acetamidophenylglucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/83939/record/SDF/?record_type=3d&response_type=display" hugo new 4-acetaminophen_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/500/record/SDF/?record_type=3d&response_type=display" hugo new 4-guanidinobutanoate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/151012/record/SDF/?record_type=3d&response_type=display" hugo new 4-hydroxyhippurate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/127/record/SDF/?record_type=3d&response_type=display" hugo new 4-hydroxyphenylacetate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/440731/record/SDF/?record_type=3d&response_type=display" hugo new 4-hydroxyphenylacetylglutamine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/129848880/record/SDF/?record_type=3d&response_type=display" hugo new 4-methylcatechol_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/7144/record/SDF/?record_type=3d&response_type=display" hugo new 4-methylguaiacol_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/123986/record/SDF/?record_type=3d&response_type=display" hugo new 5-galactosylhydroxy-L-lysine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/94312/record/SDF/?record_type=3d&response_type=display" hugo new 5,6-dihydrouridine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/88299/record/SDF/?record_type=3d&response_type=display" hugo new 5-acetylamino-6-amino-3-methyluracil.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/16054/record/SDF/?record_type=3d&response_type=display" hugo new 5-hydroxyindole_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/439904/record/SDF/?record_type=3d&response_type=display" hugo new 5-methylthioribose.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/122198196/record/SDF/?record_type=3d&response_type=display" hugo new 6-hydroxyindole_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/69160/record/SDF/?record_type=3d&response_type=display" hugo new 7-methylurate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/36573/record/SDF/?record_type=3d&response_type=display" hugo new acesulfame.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/91826562/record/SDF/?record_type=3d&response_type=display" hugo new adipoylcarnitine_C6-DC.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/203/record/SDF/?record_type=3d&response_type=display" hugo new allantoic_acid.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/87310/record/SDF/?record_type=3d&response_type=display" hugo new alliin.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/99289/record/SDF/?record_type=3d&response_type=display" hugo new allo-threonine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/134819285/record/SDF/?record_type=3d&response_type=display" hugo new alpha-CEHC_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/114962/record/SDF/?record_type=3d&response_type=display" hugo new alpha-hydroxymetoprolol.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/48/record/SDF/?record_type=3d&response_type=display" hugo new alpha-ketoglutaramate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/5459842/record/SDF/?record_type=3d&response_type=display" hugo new anthranilate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/94154/record/SDF/?record_type=3d&response_type=display" hugo new arabitol/xylitol.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/5460056/record/SDF/?record_type=3d&response_type=display" hugo new arabonate/xylonate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/5460857/record/SDF/?record_type=3d&response_type=display" hugo new argininate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/2266/record/SDF/?record_type=3d&response_type=display" hugo new azelate_C9-DC.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/2572/record/SDF/?record_type=3d&response_type=display" hugo new carboxyethyl-GABA.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/75124209/record/SDF/?record_type=3d&response_type=display" hugo new catechol_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/3083879/record/SDF/?record_type=3d&response_type=display" hugo new catechol_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/21775807/record/SDF/?record_type=3d&response_type=display" hugo new C-glycosyltryptophan.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/892/record/SDF/?record_type=3d&response_type=display" hugo new chiro-inositol.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/709625/record/SDF/?record_type=3d&response_type=display" hugo new cinnamoylglycine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/5461073/record/SDF/?record_type=3d&response_type=display" hugo new cis-urocanate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/5461090/record/SDF/?record_type=3d&response_type=display" hugo new citraconate/glutaconate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/125853/record/SDF/?record_type=3d&response_type=display" hugo new cortolone_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/7021853/record/SDF/?record_type=3d&response_type=display" hugo new cyclopro-sulfo-tyr.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/333293/record/SDF/?record_type=3d&response_type=display" hugo new cys-gly,_oxidized.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/834/record/SDF/?record_type=3d&response_type=display" hugo new cystathionine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/14308144/record/SDF/?record_type=3d&response_type=display" hugo new cysteinylglycine_disulfide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/6175/record/SDF/?record_type=3d&response_type=display" hugo new cytidine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/597/record/SDF/?record_type=3d&response_type=display" hugo new cytosine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID//record/SDF/?record_type=3d&response_type=display" hugo new decadienedioic_acid_C10:2-DC.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/134819285/record/SDF/?record_type=3d&response_type=display" hugo new delta-CEHC_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/49844181/record/SDF/?record_type=3d&response_type=display" hugo new dihydrocaffeate_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/187489/record/SDF/?record_type=3d&response_type=display" hugo new dihydroferulic_acid_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/5461056/record/SDF/?record_type=3d&response_type=display" hugo new dihydroorotate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/126041/record/SDF/?record_type=3d&response_type=display" hugo new ectoine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/2781043/record/SDF/?record_type=3d&response_type=display" hugo new erythronate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/443078/record/SDF/?record_type=3d&response_type=display" hugo new etiocholanolone_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/6305574/record/SDF/?record_type=3d&response_type=display" hugo new ferulic_acid_4-sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/439233/record/SDF/?record_type=3d&response_type=display" hugo new formiminoglutamate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/445724/record/SDF/?record_type=3d&response_type=display" hugo new fucitol.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/128869/record/SDF/?record_type=3d&response_type=display" hugo new galactonate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/121596235/record/SDF/?record_type=3d&response_type=display" hugo new gamma-CEHC_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID//record/SDF/?record_type=3d&response_type=display" hugo new glucuronide_of_C10H14O2.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID//record/SDF/?record_type=3d&response_type=display" hugo new glucuronide_of_C10H18O2.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID//record/SDF/?record_type=3d&response_type=display" hugo new glucuronide_of_C12H22O4.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID//record/SDF/?record_type=3d&response_type=display" hugo new glucuronide_of_C14H26O4.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID//record/SDF/?record_type=3d&response_type=display" hugo new glutamine_conjugate_of_C6H10O2.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID//record/SDF/?record_type=3d&response_type=display" hugo new glutamine_conjugate_of_C7H12O2.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID//record/SDF/?record_type=3d&response_type=display" hugo new glutamine_conjugate_of_C8H12O2.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID//record/SDF/?record_type=3d&response_type=display" hugo new glutamine_conjugate_of_C8H12O4.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/743/record/SDF/?record_type=3d&response_type=display" hugo new glutarate_C5-DC.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/53481699/record/SDF/?record_type=3d&response_type=display" hugo new glutarylcarnitine_C5-DC.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/10140/record/SDF/?record_type=3d&response_type=display" hugo new glycocholate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/22473/record/SDF/?record_type=3d&response_type=display" hugo new guaiacol_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/439918/record/SDF/?record_type=3d&response_type=display" hugo new guanidinosuccinate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/6857680/record/SDF/?record_type=3d&response_type=display" hugo new gulonate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/5371614/record/SDF/?record_type=3d&response_type=display" hugo new heptenedioate_C7:1-DC.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/28880746/record/SDF/?record_type=3d&response_type=display" hugo new hexanoylglutamine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/464/record/SDF/?record_type=3d&response_type=display" hugo new hippurate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/65072/record/SDF/?record_type=3d&response_type=display" hugo new homocitrulline.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/1738/record/SDF/?record_type=3d&response_type=display" hugo new homovanillate_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/782/record/SDF/?record_type=3d&response_type=display" hugo new hydantoin-5-propionate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/161220/record/SDF/?record_type=3d&response_type=display" hugo new hydroquinone_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/18645657/record/SDF/?record_type=3d&response_type=display" hugo new hydroxyasparagine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/439460/record/SDF/?record_type=3d&response_type=display" hugo new hydroxy-N6,N6,N6-trimethyllysine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/135398638/record/SDF/?record_type=3d&response_type=display" hugo new hypoxanthine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/70630/record/SDF/?record_type=3d&response_type=display" hugo new imidazole_propionate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/802/record/SDF/?record_type=3d&response_type=display" hugo new indoleacetate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/69382574/record/SDF/?record_type=3d&response_type=display" hugo new indoleacetylglutamine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/92904/record/SDF/?record_type=3d&response_type=display" hugo new indolelactate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/2733785/record/SDF/?record_type=3d&response_type=display" hugo new indoxyl_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/168379/record/SDF/?record_type=3d&response_type=display" hugo new isobutyrylcarnitine_C4.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/546304/record/SDF/?record_type=3d&response_type=display" hugo new isovalerylglycine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/3845/record/SDF/?record_type=3d&response_type=display" hugo new kynurenate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/846/record/SDF/?record_type=3d&response_type=display" hugo new kynurenine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/98504/record/SDF/?record_type=3d&response_type=display" hugo new lanthionine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/8369/record/SDF/?record_type=3d&response_type=display" hugo new maltol_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/3246006/record/SDF/?record_type=3d&response_type=display" hugo new mannonate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/74706/record/SDF/?record_type=3d&response_type=display" hugo new methyl_indole-3-acetate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/122164837/record/SDF/?record_type=3d&response_type=display" hugo new methyl-4-hydroxybenzoate_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/487/record/SDF/?record_type=3d&response_type=display" hugo new methylmalonate_MMA.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/4745115/record/SDF/?record_type=3d&response_type=display" hugo new methylsuccinate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/131802075/record/SDF/?record_type=3d&response_type=display" hugo new methylsuccinoylcarnitine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/11719/record/SDF/?record_type=3d&response_type=display" hugo new methylurea.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/892/record/SDF/?record_type=3d&response_type=display" hugo new myo-inositol.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/21863/record/SDF/?record_type=3d&response_type=display" hugo new N-2-furoylglycine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/134218393/record/SDF/?record_type=3d&response_type=display" hugo new N,N,N-trimethyl-alanylproline_betaine_TMAP.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/69698/record/SDF/?record_type=3d&response_type=display" hugo new N1-Methyl-2-pyridone-5-carboxamide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/65095/record/SDF/?record_type=3d&response_type=display" hugo new N1-methylinosine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/135501639/record/SDF/?record_type=3d&response_type=display" hugo new N2,N2-dimethylguanosine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/65977/record/SDF/?record_type=3d&response_type=display" hugo new N2,N5-diacetylornithine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/131864122/record/SDF/?record_type=3d&response_type=display" hugo new N2-acetyl,N6,N6-dimethyllysine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/131864122/record/SDF/?record_type=3d&response_type=display" hugo new N2-acetyl,N6-methyllysine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/440120/record/SDF/?record_type=3d&response_type=display" hugo new N6,N6,N6-trimethyllysine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/193344/record/SDF/?record_type=3d&response_type=display" hugo new N6,N6-dimethyllysine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/161466/record/SDF/?record_type=3d&response_type=display" hugo new N6-carbamoylthreonyladenosine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/23400779/record/SDF/?record_type=3d&response_type=display" hugo new N6-carboxyethyllysine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/14803430/record/SDF/?record_type=3d&response_type=display" hugo new N6-succinyladenosine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/53859791/record/SDF/?record_type=3d&response_type=display" hugo new N-acetyl-1-methylhistidine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/95555/record/SDF/?record_type=3d&response_type=display" hugo new N-acetyl-2-aminooctanoate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/193270/record/SDF/?record_type=3d&response_type=display" hugo new N-acetyl-3-methylhistidine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/122164824/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylalliin.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/99715/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylasparagine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/65065/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylaspartate_NAA.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/188803/record/SDF/?record_type=3d&response_type=display" hugo new N-acetyl-aspartyl-glutamate_NAAG.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/9903482/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylcarnosine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/11506771/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylcitrulline.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/123826/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylglucosaminylasparagine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/70914/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylglutamate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/75619/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylhistidine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID//record/SDF/?record_type=3d&response_type=display" hugo new N-acetylhomocitrulline.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/306109/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylisoleucine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/171763/record/SDF/?record_type=3d&response_type=display" hugo new N-acetyl-isoputreanine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/54201144/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylkynurenine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/448580/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylmethionine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/193368/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylmethionine_sulfoxide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/439197/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylneuraminate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/2000/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylphenylalanine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/152467/record/SDF/?record_type=3d&response_type=display" hugo new N-acetyl-S-allyl-L-cysteine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/65249/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylserine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/159864/record/SDF/?record_type=3d&response_type=display" hugo new N-acetyltaurine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/152204/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylthreonine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/2002/record/SDF/?record_type=3d&response_type=display" hugo new N-acetyltryptophan.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/66789/record/SDF/?record_type=3d&response_type=display" hugo new N-acetylvaline.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/426409/record/SDF/?record_type=3d&response_type=display" hugo new N-carbamoylalanine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/5151292/record/SDF/?record_type=3d&response_type=display" hugo new N-carbamoylvaline.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/439750/record/SDF/?record_type=3d&response_type=display" hugo new N-formylmethionine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/237040/record/SDF/?record_type=3d&response_type=display" hugo new N-methylhydroxyproline.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/849/record/SDF/?record_type=3d&response_type=display" hugo new N-methylpipecolate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID//record/SDF/?record_type=3d&response_type=display" hugo new nonenedioate_C9:1-DC.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/92751/record/SDF/?record_type=3d&response_type=display" hugo new orotidine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/514186/record/SDF/?record_type=3d&response_type=display" hugo new O-sulfo-L-tyrosine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/439251/record/SDF/?record_type=3d&response_type=display" hugo new pantoate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/154035/record/SDF/?record_type=3d&response_type=display" hugo new p-cresol_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/4615423/record/SDF/?record_type=3d&response_type=display" hugo new p-cresol_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/638122/record/SDF/?record_type=3d&response_type=display" hugo new pentose_acid.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/87235/record/SDF/?record_type=3d&response_type=display" hugo new phenol_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/74426/record/SDF/?record_type=3d&response_type=display" hugo new phenol_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/47579/record/SDF/?record_type=3d&response_type=display" hugo new phenylacetylalanine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/92258/record/SDF/?record_type=3d&response_type=display" hugo new phenylacetylglutamate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/92258/record/SDF/?record_type=3d&response_type=display" hugo new phenylacetylglutamine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/68144/record/SDF/?record_type=3d&response_type=display" hugo new phenylacetylglycine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/448580/record/SDF/?record_type=3d&response_type=display" hugo new phenylacetylmethionine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/99478/record/SDF/?record_type=3d&response_type=display" hugo new phenylacetylserine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/68646978/record/SDF/?record_type=3d&response_type=display" hugo new phenylacetylthreonine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/11788622/record/SDF/?record_type=3d&response_type=display" hugo new picolinoylglycine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/385/record/SDF/?record_type=3d&response_type=display" hugo new pimelate_C7-DC.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/6426709/record/SDF/?record_type=3d&response_type=display" hugo new prolylglycine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/15047/record/SDF/?record_type=3d&response_type=display" hugo new pseudouridine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/54718173/record/SDF/?record_type=3d&response_type=display" hugo new pyridoxate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/6508/record/SDF/?record_type=3d&response_type=display" hugo new quinate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/1066/record/SDF/?record_type=3d&response_type=display" hugo new quinolinate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/5460050/record/SDF/?record_type=3d&response_type=display" hugo new ribonate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/7847/record/SDF/?record_type=3d&response_type=display" hugo new S-3-hydroxypropylmercapturic_acid_HPMA.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/439155/record/SDF/?record_type=3d&response_type=display" hugo new S-adenosylhomocysteine_SAH.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/121596205/record/SDF/?record_type=3d&response_type=display" hugo new salicyluric_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/23618202/record/SDF/?record_type=3d&response_type=display" hugo new S-carboxyethylcysteine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/10457/record/SDF/?record_type=3d&response_type=display" hugo new suberate_C8-DC.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/71464531/record/SDF/?record_type=3d&response_type=display" hugo new suberoylcarnitine_C8-DC.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/1738118/record/SDF/?record_type=3d&response_type=display" hugo new succinoyltaurine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/1117/record/SDF/?record_type=3d&response_type=display" hugo new sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/7041/record/SDF/?record_type=3d&response_type=display" hugo new syringol_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/3806114/record/SDF/?record_type=3d&response_type=display" hugo new tartarate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/5570/record/SDF/?record_type=3d&response_type=display" hugo new trigonelline_N'-methylnicotinate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/1145/record/SDF/?record_type=3d&response_type=display" hugo new trimethylamine_N-oxide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/153005/record/SDF/?record_type=3d&response_type=display" hugo new tyramine_O-sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/160637/record/SDF/?record_type=3d&response_type=display" hugo new vanillactate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/178806/record/SDF/?record_type=3d&response_type=display" hugo new vanillate_glucuronide.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/3083688/record/SDF/?record_type=3d&response_type=display" hugo new vanillic_acid_glycine.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/102599558/record/SDF/?record_type=3d&response_type=display" hugo new vanillic_alcohol_sulfate.md
moleculeURL="https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/CID/736172/record/SDF/?record_type=3d&response_type=display" hugo new vanillylmandelate_VMA.md
