baseURL = "https://toxipedia.github.io/"
languageCode = "en-us"
title = "Toxipedia"
theme = 'hugo-theme-diary'
relativeURLs = true
#cannonifyURLs = true
#[[menu.main]]
#url = "/middle"
#name = "middle molecules"
#weight = 3

#[[menu.main]]
#url = "/water-soluble"
#name = "water soluble molecules"
#weight = 2


#[[menu.main]]
#url = "/protein-bound"
#name = "protein bound molecules"
#weight = 1


[[menu.main]]
url = "/categories"
name = "Categories"
weight = 1

[[menu.main]]
url = "/tags"
name = "Clinical Implications"
weight = 2

[[menu.main]]
url = "/about"
name = "About this website"
weight = 3

[[menu.main]]
url = "index.xml"
name = "RSS Feed"
weight = 4

[taxonomies]
   tag = "tags"
   category = "categories"

#[markup.goldmark.renderer]
#    unsafe = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "native"
    tabWidth = 4

[params]
    googleSearchCode = "322f0dab4559c4967"
